/**
 * Author:  20jz0134
 * Created: 2022/01/27
 */

-- DELETE FROM EMPLOYEES;

INSERT INTO EMPLOYEES(EMPLOYEE_NO, PASSWORD, NAME, POST) VALUES('M001', 'M001', 'ジョブズ', '1');
INSERT INTO EMPLOYEES(EMPLOYEE_NO, PASSWORD, NAME, POST) VALUES('M002', 'M002', 'ザッカーバーグ', '1');
INSERT INTO EMPLOYEES(EMPLOYEE_NO, PASSWORD, NAME, POST) VALUES('E001', 'E001', '陳', '2');
INSERT INTO EMPLOYEES(EMPLOYEE_NO, PASSWORD, NAME, POST) VALUES('E002', 'E002', '中川', '2');

